spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_management?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Nhox_sok_9x
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
